config/routes.rb
Rails.application.routes.draw do

 
  resources :ifp_plan_benefits

  resources :ifp_plan_quotes do
    get 'pull_data', on: :collection
    post 'pull_datas', on: :collection
    get 'index', on: :collection
  end

  resources :plan_details_for_individual_or_families

  resources :plans_for_individual_or_families do
    get 'pull_data', on: :collection
    post 'pull_datas', on: :collection
    get 'index', on: :collection
  end

  root to: "plans_for_individual_or_families#pull_data"

end

app/models/ifp_plan_quote.rb
class IfpPlanQuote < ActiveRecord::Base


	scope :exist_plan_id, ->(plan_id) { where(:plan_id => plan_id) }
	
end

app/controllers/ifp_plan_quotes_controller.rb
class IfpPlanQuotesController < ApplicationController
  before_action :set_ifp_plan_quote, only: [:show, :edit, :update, :destroy]

  # GET /ifp_plan_quotes
  # GET /ifp_plan_quotes.json
  def index
    @ifp_plan_quotes = IfpPlanQuote.all
  end

  # GET /ifp_plan_quotes/1
  # GET /ifp_plan_quotes/1.json
  def show
  end

  # GET /ifp_plan_quotes/new
  def new
    @ifp_plan_quote = IfpPlanQuote.new
  end

  def pull_datas
    plan = ProviderDataV3.new
    plan.extract_counties
    redirect_to(:controller => 'ifp_plan_quotes', :action => 'index')
  end
  # GET /ifp_plan_quotes/1/edit
  def edit
  end

  # POST /ifp_plan_quotes
  # POST /ifp_plan_quotes.json
  def create
    @ifp_plan_quote = IfpPlanQuote.new(ifp_plan_quote_params)

    respond_to do |format|
      if @ifp_plan_quote.save
        format.html { redirect_to @ifp_plan_quote, notice: 'Ifp plan quote was successfully created.' }
        format.json { render :show, status: :created, location: @ifp_plan_quote }
      else
        format.html { render :new }
        format.json { render json: @ifp_plan_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ifp_plan_quotes/1
  # PATCH/PUT /ifp_plan_quotes/1.json
  def update
    respond_to do |format|
      if @ifp_plan_quote.update(ifp_plan_quote_params)
        format.html { redirect_to @ifp_plan_quote, notice: 'Ifp plan quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @ifp_plan_quote }
      else
        format.html { render :edit }
        format.json { render json: @ifp_plan_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ifp_plan_quotes/1
  # DELETE /ifp_plan_quotes/1.json
  def destroy
    @ifp_plan_quote.destroy
    respond_to do |format|
      format.html { redirect_to ifp_plan_quotes_url, notice: 'Ifp plan quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ifp_plan_quote
      @ifp_plan_quote = IfpPlanQuote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ifp_plan_quote_params
      params[:ifp_plan_quote]
    end
end

app/helpers/ifp_plan_quotes_helper.rb
module IfpPlanQuotesHelper
end

app/views/ifp_plan_quotes/_form.html.erb
<%= form_for(@ifp_plan_quote) do |f| %>
  <% if @ifp_plan_quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ifp_plan_quote.errors.count, "error") %> prohibited this ifp_plan_quote from being saved:</h2>

      <ul>
      <% @ifp_plan_quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ifp_plan_quotes/edit.html.erb
<h1>Editing ifp_plan_quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @ifp_plan_quote %> |
<%= link_to 'Back', ifp_plan_quotes_path %>

app/views/ifp_plan_quotes/index.html.erb
<h1>Listing ifp_plan_quotes</h1>


<%= form_tag(pull_datas_ifp_plan_quotes_path) do -%>
  <table class="table">
    <tbody>
      <tr>
        
        <td>
          <input type="submit" name="submit" value="Pull datas" >
        </td>

      </tr>
    </tbody>
  </table>  
<% end -%>

  
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ifp_plan_quotes.each do |ifp_plan_quote| %>
      <tr>
        <td><%= link_to 'Show', ifp_plan_quote %></td>
        <td><%= link_to 'Edit', edit_ifp_plan_quote_path(ifp_plan_quote) %></td>
        <td><%= link_to 'Destroy', ifp_plan_quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ifp plan quote', new_ifp_plan_quote_path %>

app/views/ifp_plan_quotes/new.html.erb
<h1>New ifp_plan_quote</h1>

<%= render 'form' %>

<%= link_to 'Back', ifp_plan_quotes_path %>

app/views/ifp_plan_quotes/pull_data.html.erb
<h2>Pull Data</h2>


<div class="state_message"></div>
<%= form_tag(pull_datas_plans_for_individual_or_families_path) do -%>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= label_tag 'CountywOneZipCode', 'ZipCode' %>
        </td>
        <td>

          <%= select_tag "USA_state_code", options_for_select($USA_zip_codes.keys(), "ALL") %>
        </td>

        <td>
          <%= label_tag 'GenderType', 'Gender Type' %>
          
        </td>
        <td>
          <%= select_tag "sex", options_for_select([ "Male", "Female" ], "Male") %>
        </td>

        <td>
          <%= label_tag 'age', 'Age' %>
        </td>
        <td>
          <%= number_field_tag 'age_from', 27, in: 27...65 %> from
          <%= number_field_tag 'age_to', 27, in: 27...65 %> to
        </td>

        <td>
          <%= label_tag 'TobaccoUser', 'Tobacco User' %>
        </td>
        <td>
          <%= select_tag "tobacco_type", options_for_select([ "Non-Smoker", "Smoker" ], "Non-Smoker") %>
        </td>

        <td>
          <input type="submit" name="submit" value="Pull IFPPlans" onclick="validate_filters();">
        </td>

      </tr>
    </tbody>
  </table>  
<% end -%>



<!-- <table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans_for_individual_or_families.each do |plans_for_individual_or_family| %>
      <tr>
        <td><%= link_to 'Show', plans_for_individual_or_family %></td>
        <td><%= link_to 'Edit', edit_plans_for_individual_or_family_path(plans_for_individual_or_family) %></td>
        <td><%= link_to 'Destroy', plans_for_individual_or_family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<br>


app/views/ifp_plan_quotes/pull_datas.html.erb
<h2>Pull Datas</h2>
<%= @display_data %>
<br>

<%= @parse_xml %>




app/views/ifp_plan_quotes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ifp_plan_quote_path(@ifp_plan_quote) %> |
<%= link_to 'Back', ifp_plan_quotes_path %>