config/routes.rb
Rails.application.routes.draw do

 
  resources :ifp_plan_benefits

  resources :ifp_plan_quotes do
    get 'pull_data', on: :collection
    post 'pull_datas', on: :collection
    get 'index', on: :collection
  end

  resources :plan_details_for_individual_or_families

  resources :plans_for_individual_or_families do
    get 'pull_data', on: :collection
    post 'pull_datas', on: :collection
    get 'index', on: :collection
  end

  root to: "plans_for_individual_or_families#pull_data"

end

app/models/ifp_plan_benefit.rb
class IfpPlanBenefit < ActiveRecord::Base

	scope :get_plan_benefit_by_plan_id, ->(plan_id) { where(:plan_id => plan_id)}

end

app/controllers/ifp_plan_benefits_controller.rb
class IfpPlanBenefitsController < ApplicationController
  before_action :set_ifp_plan_benefit, only: [:show, :edit, :update, :destroy]

  # GET /ifp_plan_benefits
  # GET /ifp_plan_benefits.json
  def index
    @ifp_plan_benefits = IfpPlanBenefit.all
  end

  # GET /ifp_plan_benefits/1
  # GET /ifp_plan_benefits/1.json
  def show
  end

  # GET /ifp_plan_benefits/new
  def new
    @ifp_plan_benefit = IfpPlanBenefit.new
  end

  # GET /ifp_plan_benefits/1/edit
  def edit
  end

  # POST /ifp_plan_benefits
  # POST /ifp_plan_benefits.json
  def create
    @ifp_plan_benefit = IfpPlanBenefit.new(ifp_plan_benefit_params)

    respond_to do |format|
      if @ifp_plan_benefit.save
        format.html { redirect_to @ifp_plan_benefit, notice: 'Ifp plan benefit was successfully created.' }
        format.json { render :show, status: :created, location: @ifp_plan_benefit }
      else
        format.html { render :new }
        format.json { render json: @ifp_plan_benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ifp_plan_benefits/1
  # PATCH/PUT /ifp_plan_benefits/1.json
  def update
    respond_to do |format|
      if @ifp_plan_benefit.update(ifp_plan_benefit_params)
        format.html { redirect_to @ifp_plan_benefit, notice: 'Ifp plan benefit was successfully updated.' }
        format.json { render :show, status: :ok, location: @ifp_plan_benefit }
      else
        format.html { render :edit }
        format.json { render json: @ifp_plan_benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ifp_plan_benefits/1
  # DELETE /ifp_plan_benefits/1.json
  def destroy
    @ifp_plan_benefit.destroy
    respond_to do |format|
      format.html { redirect_to ifp_plan_benefits_url, notice: 'Ifp plan benefit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ifp_plan_benefit
      @ifp_plan_benefit = IfpPlanBenefit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ifp_plan_benefit_params
      params[:ifp_plan_benefit]
    end
end

app/helpers/ifp_plan_benefits_helper.rb
module IfpPlanBenefitsHelper
end

app/views/ifp_plan_benefits/_form.html.erb
<%= form_for(@ifp_plan_benefit) do |f| %>
  <% if @ifp_plan_benefit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ifp_plan_benefit.errors.count, "error") %> prohibited this ifp_plan_benefit from being saved:</h2>

      <ul>
      <% @ifp_plan_benefit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ifp_plan_benefits/edit.html.erb
<h1>Editing ifp_plan_benefit</h1>

<%= render 'form' %>

<%= link_to 'Show', @ifp_plan_benefit %> |
<%= link_to 'Back', ifp_plan_benefits_path %>

app/views/ifp_plan_benefits/index.html.erb
<h1>Listing ifp_plan_benefits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ifp_plan_benefits.each do |ifp_plan_benefit| %>
      <tr>
        <td><%= link_to 'Show', ifp_plan_benefit %></td>
        <td><%= link_to 'Edit', edit_ifp_plan_benefit_path(ifp_plan_benefit) %></td>
        <td><%= link_to 'Destroy', ifp_plan_benefit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ifp plan benefit', new_ifp_plan_benefit_path %>

app/views/ifp_plan_benefits/new.html.erb
<h1>New ifp_plan_benefit</h1>

<%= render 'form' %>

<%= link_to 'Back', ifp_plan_benefits_path %>

app/views/ifp_plan_benefits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ifp_plan_benefit_path(@ifp_plan_benefit) %> |
<%= link_to 'Back', ifp_plan_benefits_path %>