config/routes.rb
Rails.application.routes.draw do

 
  resources :ifp_plan_benefits

  resources :ifp_plan_quotes do
    get 'pull_data', on: :collection
    post 'pull_datas', on: :collection
    get 'index', on: :collection
  end

  resources :plan_details_for_individual_or_families

  resources :plans_for_individual_or_families do
    get 'pull_data', on: :collection
    post 'pull_datas', on: :collection
    get 'index', on: :collection
  end

  root to: "plans_for_individual_or_families#pull_data"

end

app/models/plans_for_individual_or_family.rb
class PlansForIndividualOrFamily < ActiveRecord::Base

	scope :exist_plan_id, ->(plan_id) { where(:plan_id => plan_id) }

	def test
		plan = ProviderData.new
		print plan.USA_ZIP_CODES
	end
end

app/controllers/plans_for_individual_or_families_controller.rb
require 'rest_client'
require 'nokogiri'
require 'open-uri'






class PlansForIndividualOrFamiliesController < ApplicationController
  before_action :set_plans_for_individual_or_family, only: [:show, :edit, :update, :destroy]

  # GET /plans_for_individual_or_families
  # GET /plans_for_individual_or_families.json
  def index
    #@plans_for_individual_or_families = PlansForIndividualOrFamily.all.limit(10)
    @plans_for_individual_or_families = PlansForIndividualOrFamily.all.limit(100)
    
  end

  def pull_data
    @plans_for_individual_or_families = PlansForIndividualOrFamily.all
  end

  

  def pull_datas

    request_uri = "https://api.finder.healthcare.gov/v2.0/"


    age_from = params[:age_from].to_i
    age_to = params[:age_to].to_i
    gender_type = params[:sex]
    tobacco_type = params[:tobacco_type]
    state_code = params[:USA_state_code]

    plan_data = ProviderData.new
    plan_data.extract_data state_code,age_from,age_to,gender_type,tobacco_type 
    redirect_to(:controller => 'plans_for_individual_or_families', :action => 'index')
    
  end

  # GET /plans_for_individual_or_families/1
  # GET /plans_for_individual_or_families/1.json
  def show
  end

  # GET /plans_for_individual_or_families/new
  def new
    @plans_for_individual_or_family = PlansForIndividualOrFamily.new
  end

  # GET /plans_for_individual_or_families/1/edit
  def edit
  end

  # POST /plans_for_individual_or_families
  # POST /plans_for_individual_or_families.json
  def create
    @plans_for_individual_or_family = PlansForIndividualOrFamily.new(plans_for_individual_or_family_params)

    respond_to do |format|
      if @plans_for_individual_or_family.save
        format.html { redirect_to @plans_for_individual_or_family, notice: 'Plans for individual or family was successfully created.' }
        format.json { render :show, status: :created, location: @plans_for_individual_or_family }
      else
        format.html { render :new }
        format.json { render json: @plans_for_individual_or_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans_for_individual_or_families/1
  # PATCH/PUT /plans_for_individual_or_families/1.json
  def update
    respond_to do |format|
      if @plans_for_individual_or_family.update(plans_for_individual_or_family_params)
        format.html { redirect_to @plans_for_individual_or_family, notice: 'Plans for individual or family was successfully updated.' }
        format.json { render :show, status: :ok, location: @plans_for_individual_or_family }
      else
        format.html { render :edit }
        format.json { render json: @plans_for_individual_or_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans_for_individual_or_families/1
  # DELETE /plans_for_individual_or_families/1.json
  def destroy
    @plans_for_individual_or_family.destroy
    respond_to do |format|
      format.html { redirect_to plans_for_individual_or_families_url, notice: 'Plans for individual or family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plans_for_individual_or_family
      @plans_for_individual_or_family = PlansForIndividualOrFamily.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plans_for_individual_or_family_params
      params[:plans_for_individual_or_family]
    end
end

app/helpers/plans_for_individual_or_families_helper.rb
module PlansForIndividualOrFamiliesHelper
end

app/views/plans_for_individual_or_families/_form.html.erb
<%= form_for(@plans_for_individual_or_family) do |f| %>
  <% if @plans_for_individual_or_family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plans_for_individual_or_family.errors.count, "error") %> prohibited this plans_for_individual_or_family from being saved:</h2>

      <ul>
      <% @plans_for_individual_or_family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans_for_individual_or_families/edit.html.erb
<h1>Editing plans_for_individual_or_family</h1>

<%= render 'form' %>

<%= link_to 'Show', @plans_for_individual_or_family %> |
<%= link_to 'Back', plans_for_individual_or_families_path %>

app/views/plans_for_individual_or_families/index.html.erb
<p>
  <%= link_to 'Back to extracting', 'pull_data' %>
</p>
<h2>Listing PlansForIndividualOrFamilies</h2>

<table class="table">
  <tbody>
    <tr>
      <td>
        <%= label_tag 'CountywOneZipCode', 'ZipCode' %>
      </td>
      <td>
        <%= select_tag "county_zip_code", options_for_select([ "Alameda", "Alpine", "Amador", "Calaveras", "Colusa", "Contra Costa", "Del Norte","El Dorado", "Fresno", "Glenn", "Imperial", "Inyo", "Kern", "Lassen", "Los Angeles", "Madera", "Marin", "Mariposa", "Mendocino", "Merced", "Modoc", "Mono", "Monterey", "Napa", "Placer", "Plumas", "Riverside", "Sacramento", "San Benito", "San Bernardino", "San Diego", "San Francisco", "San Joaquin", "San Luis Obispo", "San Mateo", "Santa Barbara", "Santa Clara", "Shasta", "Siskiyou", "Solano", "Sonoma", "Stanislaus", "Sutter", "Tehama", "Tulare", "Tuolumne", "Ventura", "Yolo", "Yuba" ], "Alameda") %>
      </td>

      <td>
        <%= label_tag 'GenderType', 'Gender Type' %>
        
      </td>
      <td>
        <%= select_tag "sex", options_for_select([ "Male", "Female" ], "Male") %>
      </td>

      <td>
        <%= label_tag 'age', 'Age' %>
      </td>
      <td>
        <%= number_field_tag 'age_from', 19, in: 19...65 %> from
        <%= number_field_tag 'age_to', 19, in: 19...65 %> to
      </td>

      <td>
        <%= label_tag 'TobaccoUser', 'Tobacco User' %>
      </td>
      <td>
        <%= select_tag "tobacco_type", options_for_select([ "Non-Smoker", "Smoker" ], "Non-Smoker") %>
      </td>

      <td>
        <input type="submit" name="submit" value="Search" onclick="validate_filters();">
      </td>

    </tr>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>PlanID</th>
      <th>PlanNameText</th>
      <th>ProductNameText</th>
      <th>IssuerID</th>
      <th>ProviderType</th>
      <th>BaseRateAmount</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @plans_for_individual_or_families.each do |plans_for_individual_or_family| %>
<!--       <tr>
        <td><%= link_to 'Show', plans_for_individual_or_family %></td>
        <td><%= link_to 'Edit', edit_plans_for_individual_or_family_path(plans_for_individual_or_family) %></td>
        <td><%= link_to 'Destroy', plans_for_individual_or_family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
      <tr>
        <td>
          <%= plans_for_individual_or_family.plan_id %>
        </td>
        <td>
          <%=  truncate(plans_for_individual_or_family.plan_name_text, length: 30) %>
        </td>
        <td>
          <%= truncate(plans_for_individual_or_family.product_name_text, length: 30) %>
        </td>
        <td>
          <%= plans_for_individual_or_family.issuer_id %>
        </td>
        <td>
          <%= plans_for_individual_or_family.provider_type %>
        </td>
        <td>
          <%= plans_for_individual_or_family.base_rate_amount %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/plans_for_individual_or_families/new.html.erb
<h1>New plans_for_individual_or_family</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_for_individual_or_families_path %>

app/views/plans_for_individual_or_families/pull_data.html.erb
<h2>Pull Data</h2>


<div class="state_message"></div>
<%= form_tag(pull_datas_plans_for_individual_or_families_path) do -%>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= label_tag 'CountywOneZipCode', 'ZipCode' %>
        </td>
        <td>

          <%= select_tag "USA_state_code", options_for_select($USA_zip_codes.keys(), "ALL") %>
        </td>

        <td>
          <%= label_tag 'GenderType', 'Gender Type' %>
          
        </td>
        <td>
          <%= select_tag "sex", options_for_select([ "Male", "Female" ], "Male") %>
        </td>

        <td>
          <%= label_tag 'age', 'Age' %>
        </td>
        <td>
          <%= number_field_tag 'age_from', 19, in: 19...65 %> from
          <%= number_field_tag 'age_to', 19, in: 19...65 %> to
        </td>

        <td>
          <%= label_tag 'TobaccoUser', 'Tobacco User' %>
        </td>
        <td>
          <%= select_tag "tobacco_type", options_for_select([ "Non-Smoker", "Smoker" ], "Non-Smoker") %>
        </td>

        <td>
          <input type="submit" name="submit" value="Pull datas" onclick="validate_filters();">
        </td>

      </tr>
    </tbody>
  </table>  
<% end -%>



<!-- <table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans_for_individual_or_families.each do |plans_for_individual_or_family| %>
      <tr>
        <td><%= link_to 'Show', plans_for_individual_or_family %></td>
        <td><%= link_to 'Edit', edit_plans_for_individual_or_family_path(plans_for_individual_or_family) %></td>
        <td><%= link_to 'Destroy', plans_for_individual_or_family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<br>


app/views/plans_for_individual_or_families/pull_datas.html.erb
<h2>Pull Datas</h2>
<%= @display_data %>
<br>

<%= @parse_xml %>




app/views/plans_for_individual_or_families/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_plans_for_individual_or_family_path(@plans_for_individual_or_family) %> |
<%= link_to 'Back', plans_for_individual_or_families_path %>